# Generated by Django 2.2.5 on 2019-10-02 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido del usuario')),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo de la persona')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio del usuario')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono del usuario')),
                ('correoElectronico', models.EmailField(max_length=254, verbose_name='Correo electronico del usuario')),
                ('estado', models.BooleanField(default=False, verbose_name='Usuario activo/inactivo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Alumno')),
                ('gustoMusical', models.CharField(max_length=300, verbose_name='Musica que prefiere ejecutar el alumno')),
                ('conocimientoPrevio', models.TextField(blank=True, null=True, verbose_name='El nivel que tiene el alumno')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreIdentificador', models.CharField(max_length=150, verbose_name='Nombre de compositor')),
            ],
            options={
                'verbose_name': 'Compositor',
                'verbose_name_plural': 'Compositor',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la especialidad')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la especialidad')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tema')),
                ('descripcion', models.TextField(verbose_name='Descripcion del tema')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nivel del tema')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de la tema')),
                ('archivo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del usuario')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido del usuario')),
                ('fechaNac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo de la persona')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio del usuario')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono del usuario')),
                ('correoElectronico', models.EmailField(max_length=254, verbose_name='Correo electronico del usuario')),
                ('estado', models.BooleanField(default=False, verbose_name='Usuario activo/inactivo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones del Profesor')),
                ('especialidades', models.ManyToManyField(blank=True, to='gestionMusical.Especialidad')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
            },
        ),
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la partitura')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('archivo', models.BinaryField(blank=True, null=True)),
                ('nivel', models.CharField(max_length=100, verbose_name='Nivel de la partitura')),
                ('compositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Compositor')),
                ('especialidadesAcordes', models.ManyToManyField(blank=True, to='gestionMusical.Especialidad')),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la clase')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la clase')),
                ('diaSemanal', models.CharField(max_length=100, verbose_name='dia de la semana')),
                ('horaInicio', models.CharField(max_length=50, verbose_name='hora de inicio')),
                ('duracion', models.IntegerField(default=0, verbose_name='duracion de la clase')),
                ('alumnoAsociados', models.ManyToManyField(default=None, to='gestionMusical.Alumno')),
                ('profesorCargo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Profesor')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='especialidadRequerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Especialidad'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='partiturasAsociadas',
            field=models.ManyToManyField(to='gestionMusical.Partitura'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='temasAsociadas',
            field=models.ManyToManyField(to='gestionMusical.Tema'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
