# Generated by Django 2.2.5 on 2019-11-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la recomendacion')),
                ('descripcion', models.TextField(verbose_name='en q consiste la reco de practica')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion de la recomendacion')),
                ('fechaCierre', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estadoReco', models.BooleanField(default=False, verbose_name='estado de reco activo/inactivo')),
                ('alumnoReco', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Alumno')),
                ('partiMusicReco', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Partitura')),
                ('profesorReferencia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Profesor')),
            ],
            options={
                'verbose_name': 'Recomendacion',
                'verbose_name_plural': 'Recomendaciones',
            },
        ),
    ]
