# Generated by Django 2.2.5 on 2020-02-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='claseReferencia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Clase'),
        ),
    ]
