# Generated by Django 2.2.5 on 2019-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitura',
            name='especialidadesAcordes',
            field=models.ManyToManyField(blank=True, null=True, to='gestionMusical.Especialidad'),
        ),
    ]
