# Generated by Django 2.2.5 on 2019-11-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='duracionDias',
            field=models.IntegerField(default=1, verbose_name='duracion de la prestamo'),
        ),
    ]
