# Generated by Django 2.2.5 on 2019-11-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='historica',
            field=models.BooleanField(default=False, verbose_name='estado de clase en tiempo activo/inactivo'),
        ),
    ]
