# Generated by Django 2.2.5 on 2019-11-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': (('es_alumno', 'es alumno'), ('es_pre_alumno', 'es pre alumno')), 'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'permissions': (('es_profesor', 'es profesor'), ('es_pre_profesor', 'es pre profesor'), ('es_director', 'es director')), 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
