# Generated by Django 2.2.5 on 2019-09-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='alumnoAsociados',
            field=models.ManyToManyField(default=None, to='gestionMusical.Alumno'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='partiturasAsignados',
            field=models.ManyToManyField(default=None, to='gestionMusical.Partitura'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesorCargo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Profesor'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='temasAsignados',
            field=models.ManyToManyField(default=None, to='gestionMusical.Tema'),
        ),
    ]
