# Generated by Django 2.2.5 on 2019-09-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Usuario activo/inactivo'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Usuario activo/inactivo'),
        ),
    ]
