# Generated by Django 2.2.5 on 2019-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_clase_historica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='horaInicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
