# Generated by Django 2.2.5 on 2019-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_auto_20191025_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='telefonoTutor',
            field=models.CharField(default=1, max_length=20, verbose_name='telefono del usuario'),
            preserve_default=False,
        ),
    ]
