# Generated by Django 2.2.5 on 2019-10-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_auto_20191007_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='historiaPrevia',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Profesor'),
        ),
    ]
