# Generated by Django 2.2.5 on 2019-09-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='telefono del usuario'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='telefono del usuario'),
        ),
    ]
