# Generated by Django 2.2.5 on 2019-09-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_auto_20190913_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='partiturasAsignados',
        ),
        migrations.RemoveField(
            model_name='clase',
            name='temasAsignados',
        ),
        migrations.AddField(
            model_name='tema',
            name='archivoURL',
            field=models.TextField(default=1, verbose_name='url de la tema'),
            preserve_default=False,
        ),
    ]
