# Generated by Django 2.2.5 on 2019-09-09 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_auto_20190909_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='profesorCargo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Profesor'),
        ),
    ]
