# Generated by Django 2.2.5 on 2019-09-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_auto_20190924_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='conocimientoPrevio',
            field=models.TextField(blank=True, null=True, verbose_name='El nivel que tiene el alumno'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
