# Generated by Django 2.2.5 on 2019-11-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_prestamo_duraciondias'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='instrumentoPrestado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Instrumento'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estadoProfesor',
            field=models.CharField(max_length=100, verbose_name='Tipo profe del prestamo'),
        ),
    ]
