# Generated by Django 2.2.5 on 2020-02-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0002_recomendacion_clasereferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstrumento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activo/inactivo'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='activo/inactivo'),
        ),
    ]
