# Generated by Django 2.2.5 on 2019-11-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cupo',
            field=models.IntegerField(default=0, verbose_name='cupo clase'),
        ),
        migrations.AddField(
            model_name='clase',
            name='especialidadesDar',
            field=models.ManyToManyField(default=None, to='gestionMusical.Especialidad'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel',
            field=models.CharField(default=1, max_length=50, verbose_name='Nivel de la clase'),
            preserve_default=False,
        ),
    ]
