# Generated by Django 2.2.5 on 2019-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_auto_20190905_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la especialidad')),
                ('descripcion', models.TextField(verbose_name='Descripcion de la especialidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Usuario activo/inactivo')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.AddField(
            model_name='profesor',
            name='especialidades',
            field=models.ManyToManyField(to='gestionMusical.Especialidad'),
        ),
    ]
