# Generated by Django 2.2.5 on 2019-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_auto_20190909_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='alumnoAsociados',
            field=models.ManyToManyField(default=None, null=True, to='gestionMusical.Alumno'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='partiturasAsignados',
            field=models.ManyToManyField(default=None, null=True, to='gestionMusical.Partitura'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='temasAsignados',
            field=models.ManyToManyField(default=None, null=True, to='gestionMusical.Tema'),
        ),
    ]
