# Generated by Django 2.2.5 on 2019-10-14 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_profesor_historiaprevia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicaTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del musica')),
            ],
            options={
                'verbose_name': 'Musica',
                'verbose_name_plural': 'Musicas',
            },
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='gustoMusical',
        ),
        migrations.AddField(
            model_name='alumno',
            name='musica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.MusicaTipo'),
        ),
    ]
