# Generated by Django 2.2.5 on 2019-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_auto_20190924_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='especialidades',
            field=models.ManyToManyField(null=True, to='gestionMusical.Especialidad'),
        ),
    ]
