# Generated by Django 2.2.5 on 2020-02-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0003_auto_20200207_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Nombre de la imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion de la imagen')),
                ('link', models.CharField(blank=True, max_length=400, null=True, verbose_name='link de la imagen')),
                ('archivo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
