# Generated by Django 2.2.5 on 2019-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_auto_20190925_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='especialidades',
            field=models.ManyToManyField(blank=True, null=True, to='gestionMusical.Especialidad'),
        ),
    ]
