# Generated by Django 2.2.5 on 2019-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_remove_horario_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fechaCreacion',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horarios',
            field=models.ManyToManyField(default=None, to='gestionMusical.Horario'),
        ),
    ]
