# Generated by Django 2.2.5 on 2019-10-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_auto_20191013_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitura',
            name='especialidadesAcordes',
            field=models.ManyToManyField(blank=True, to='gestionMusical.Especialidad'),
        ),
    ]
