# Generated by Django 2.2.5 on 2019-09-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_partitura_archivourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='archivoURL',
            field=models.CharField(max_length=500, verbose_name='url de la tema'),
        ),
    ]
