# Generated by Django 2.2.5 on 2019-11-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_auto_20191114_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.CharField(default=1, max_length=100, verbose_name='Nivel de la partitura'),
            preserve_default=False,
        ),
    ]
