# Generated by Django 2.2.5 on 2019-10-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del instrumento')),
                ('descripcion', models.TextField(verbose_name='Descripcion del instrumento')),
                ('color', models.CharField(max_length=100, verbose_name='color del instrumento')),
                ('estadoUso', models.CharField(max_length=100, verbose_name='estado de uso del instrumento')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('archivo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
            },
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'Prestamo', 'verbose_name_plural': 'Prestamos'},
        ),
    ]
