# Generated by Django 2.2.5 on 2019-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_auto_20190905_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Especialidad activo/inactivo'),
        ),
    ]
