# Generated by Django 2.2.5 on 2020-02-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0004_filmina'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='archivo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalalumno',
            name='archivo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprofesor',
            name='archivo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='archivo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
