# Generated by Django 2.2.5 on 2019-11-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0005_auto_20191125_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='horarios',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Horario'),
        ),
    ]
