# Generated by Django 2.2.5 on 2019-10-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0005_auto_20191013_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tutor')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido del tutor')),
                ('tipo', models.CharField(max_length=30, verbose_name='que relacion de tutor es')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Tutor'),
        ),
    ]
