# Generated by Django 2.2.5 on 2019-09-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0005_auto_20190925_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='gestionMusical.Especialidad'),
        ),
    ]
