# Generated by Django 2.2.5 on 2019-09-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0005_auto_20190909_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='partitura',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='estado',
        ),
        migrations.AlterField(
            model_name='clase',
            name='profesorCargo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestionMusical.Profesor'),
        ),
    ]
