# Generated by Django 2.2.5 on 2019-09-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0006_auto_20190918_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitura',
            name='tipoDescripto',
        ),
    ]
