# Generated by Django 2.2.5 on 2019-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0006_auto_20190926_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitura',
            name='archivoURL',
        ),
        migrations.AddField(
            model_name='partitura',
            name='archivo',
            field=models.ImageField(null=True, upload_to='partitura'),
        ),
    ]
