# Generated by Django 2.2.5 on 2019-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0006_auto_20191125_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='creada',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion de la asistencia'),
        ),
    ]
