# Generated by Django 2.2.5 on 2019-11-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0007_asistencia_creada'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='creadaClase',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creacion de la asistencia'),
        ),
    ]
