# Generated by Django 2.2.5 on 2019-09-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0007_remove_partitura_tipodescripto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partitura',
            name='archivoURL',
            field=models.CharField(max_length=500, verbose_name='url de la partitura'),
        ),
    ]
