# Generated by Django 2.2.5 on 2019-11-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0009_auto_20191130_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutoDato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del instituto')),
                ('telefono', models.CharField(max_length=20, verbose_name='telefono')),
                ('correoElectronico', models.EmailField(max_length=254, verbose_name='Correo electronico del usuario')),
                ('domicilio', models.CharField(max_length=100, verbose_name='Domicilio del usuario')),
                ('horario', models.CharField(max_length=100, verbose_name='horario')),
                ('archivo', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'InstitutoDato',
                'verbose_name_plural': 'InstitutoDato',
            },
        ),
    ]
