# Generated by Django 2.2.5 on 2019-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0011_prestamo_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='reputacion',
            field=models.IntegerField(default=100, verbose_name='numero de reputacion max 100'),
        ),
    ]
