# Generated by Django 2.2.5 on 2020-01-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0012_alumno_reputacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cantidadAsistida',
            field=models.IntegerField(default=0, verbose_name='cantidad de asistencias totales a clase'),
        ),
    ]
