# Generated by Django 2.2.5 on 2020-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0013_clase_cantidadasistida'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='estadoEsp',
            field=models.BooleanField(default=True, verbose_name='activo/inactivo'),
        ),
    ]
