# Generated by Django 2.2.5 on 2020-01-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0015_tutor_emailtutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tutor',
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMusical.Alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMusical.Tutor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ManyToManyField(through='gestionMusical.TipoRelacion', to='gestionMusical.Tutor'),
        ),
    ]
