# Generated by Django 2.2.5 on 2020-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0016_auto_20200126_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporelacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='que relacion de tutor es'),
        ),
    ]
