# Generated by Django 2.2.5 on 2020-01-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMusical', '0017_tiporelacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la recomendacion')),
            ],
            options={
                'verbose_name': 'TipoTarea',
                'verbose_name_plural': 'TipoTareas',
            },
        ),
    ]
